name: Frontend CD - Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  trigger-deploy:
    name: Verify & Deploy to Netlify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9
        with:
          version: 11.6.0

      - name: Set up Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 24.16.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Application
        run: pnpm build

      - name: Deploy to Netlify
        run: pnpm --package=netlify-cli dlx netlify deploy --prod --dir=dist
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
